blog/urls.py
from django.urls import path
from blog.views import *
from blog.feeds import LatestEntriesFeed

app_name = 'blog'

urlpatterns = [
    path('', blog_view, name='blog-index'),
    path('<int:pid>', blog_single, name='blog-single'),
    path('category/<str:cat_name>', blog_view, name='category'),
    path('tag/<str:tag_name>', blog_view, name='tag'),
    path('author/<str:author_username>', blog_view, name='author'),
    path('search/', blog_search, name='search'),
    path("rss/feed/", LatestEntriesFeed()),
]

modern/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.sitemaps.views import sitemap

from website.sitemaps import StaticViewSitemap
from blog.sitemaps import BlogSitemap
import debug_toolbar

sitemaps = {
    "static": StaticViewSitemap,
    "blog": BlogSitemap
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('blog/', include('blog.urls')),
    path('accounts/', include('accounts.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
    path('summernote/', include('django_summernote.urls')),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path('robots.txt', include('robots.urls')),
    path("__debug__/", include("debug_toolbar.urls")),
    path('captcha/', include('captcha.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

website/urls.py
from django.urls import path
from website.views import *

app_name = 'website'

urlpatterns = [
    path('', index_view, name='index'),
    path('about', about_view, name='about'),
    path('contact', contact_view, name='contact'),
    path('services', services_view, name='services'),
    path('team', team_view, name='team'),
    path('newsletter', newsletter_view, name='newsletter')
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return str(self.name)


class Post (models.Model):
    image = models.ImageField(upload_to='blog/', default='blog/default.jpg')
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    order = models.IntegerField(default=0)
    title = models.CharField(max_length=255)
    content = models.TextField()
    tags = TaggableManager(blank=True)
    category = models.ManyToManyField(Category)
    counted_views = models.IntegerField(default=0)
    status = models.BooleanField(default=False)
    login_require = models.BooleanField(default=False)
    published_date = models.DateTimeField(null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_date']

    def __str__(self):
        return str(self.title)

    def get_absolute_url(self):
        return reverse("blog:blog-single", kwargs={"pid": self.id})


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    email = models.EmailField()
    subject = models.CharField(max_length=255)
    message = models.TextField()
    approved = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_date']

    def __str__(self):
        return str(self.name)

blog/forms.py
from django import forms
from django.forms import ModelForm
from blog.models import Comment


class CommentForm(ModelForm):

    class Meta:
        model = Comment
        fields = ['post', 'name', 'email', 'subject', 'message']

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from blog.models import Post, Comment
from django.db.models.functions import Now
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from blog.forms import CommentForm
from django.contrib import messages

# Create your views here.


def blog_view(request, **kwargs):

    posts = Post.objects.filter(status=1)
    if kwargs.get('cat_name') != None:
        lowercase_cat_name = kwargs['cat_name'].lower()
        posts = posts.filter(category__name__iexact=lowercase_cat_name)
    if kwargs.get('author_username') != None:
        lowercase_author_username = kwargs['author_username'].lower()
        posts = posts.filter(
            author__username__iexact=lowercase_author_username)
    if kwargs.get('tag_name') != None:
        lowercase_tag_name = kwargs['tag_name'].lower()
        posts = posts.filter(
            tags__name__iexact=lowercase_tag_name)
    posts = Paginator(posts, 3)
    try:
        page_number = request.GET.get('page')
        posts = posts.get_page(page_number)
    except PageNotAnInteger:
        posts = posts.get_page(1)
    except EmptyPage:
        posts = posts.get_page(1)
    context = {'posts': posts}
    return render(request, 'blog/blog.html', context)


def blog_single(request, pid):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            form.save()
            messages.add_message(request, messages.SUCCESS,
                                 'Your comment has been received successfully!!!')
        else:
            messages.add_message(request, messages.ERROR,
                                 'Your comment didn\'t received!!!')
    posts = Post.objects.filter(
        published_date__lte=Now(), status=1).order_by('order')
    post = get_object_or_404(posts, pk=pid)
    if not post.login_require:
        current_index = list(posts).index(post)

        previous_post = None
        next_post = None

        if current_index > 0:
            previous_post = posts[current_index - 1]

        if current_index < len(posts) - 1:
            next_post = posts[current_index + 1]

        comments = Comment.objects.filter(
            post=post.id, approved=True)

        form = CommentForm()
        context = {'post': post, 'comments': comments, 'form': form, 'previous_post': previous_post,
                   'next_post': next_post}
        post.counted_views += 1
        post.save()
        return render(request, 'blog/blog-single.html', context)
    else:
        return redirect('/accounts/login')


def blog_search(request):
    posts = Post.objects.filter(status=1)
    if request.method == 'GET':
        # request.GET.get('s')
        posts = posts.filter(content__contains=request.GET.get(
            's')) or posts.filter(title__contains=request.GET.get('s'))
    context = {'posts': posts}
    return render(request, 'blog/blog.html', context)

templates/blog/blog-categories.html
{% load static %}

<h3 class="sidebar-title">Categories</h3>
              <div class="sidebar-item categories">
                <ul>
                  {% for name,count in categories.items %}
                    <li><a href="{% url 'blog:category' cat_name=name %}">{{name}}<span>({{count}})</span></a></li>
                  {% endfor %}
                </ul>
              </div><!-- End sidebar categories-->

templates/blog/blog-recent-posts.html
{% load static %}
{% load humanize %}

<h3 class="sidebar-title">Recent Posts</h3>
            {% for post in posts %}
              <div class="sidebar-item recent-posts">
                <div class="post-item clearfix">
                  <img src="{{post.image.url}}" alt="">
                  <h4><a href="{% url 'blog:blog-single' pid=post.id %}">{{post.title}}</a></h4>
                  <time datetime="2020-01-01">{{post.published_date|naturaltime}}</time>
                </div>
              </div><!-- End sidebar recent posts-->
            {% endfor %}

templates/blog/blog-search.html
{% load static %}

<h3 class="sidebar-title">Search</h3>
              <div class="sidebar-item search-form">
                <form action="{% url 'blog:search' %}" method="get">
                  <input type="text" name="s">
                  <button type="submit"><i class="bi bi-search"></i></button>
                </form>
              </div><!-- End sidebar search formn-->

templates/blog/blog-single.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}
{% load blog_tags %}
{% load humanize %}
{% block content %}

  <main id="main">

    <!-- ======= Blog Section ======= -->
    <section class="breadcrumbs">
      <div class="container">

        <div class="d-flex justify-content-between align-items-center">
          <h2>Blog</h2>

          <ol>
            <li><a href="{% url 'website:index' %}">Home</a></li>
            <li><a href="{% url 'blog:blog-index' %}">Blog</a></li>
            <li>Dolorum optio tempore voluptas dignissimos cumque fuga qui quibusdam quia reiciendis</li>
          </ol>
        </div>

      </div>
    </section><!-- End Blog Section -->

    <!-- ======= Blog Single Section ======= -->
    <section id="blog" class="blog">
      <div class="container" data-aos="fade-up">

        <div class="row">

          <div class="col-lg-8 entries">

            <article class="entry entry-single">

              <div class="entry-img">
                <img src="{{post.image.url}}" alt="" class="img-fluid">
              </div>

              <h2 class="entry-title">
                <a href="{% url 'blog:blog-single' pid=post.id %}">{{post.title}}</a>
              </h2>

              <div class="entry-meta">
                <ul>
                  <li class="d-flex align-items-center"><i class="bi bi-person"></i> <a href="{% url 'blog:author' author_username=post.author.username %}">{{post.author.get_full_name}}</a></li>
                  <li class="d-flex align-items-center"><i class="bi bi-clock"></i> <a href="{% url 'blog:blog-single' pid=post.id %}"><time datetime="2020-01-01">{{post.published_date|naturaltime}}</time></a></li>
                  <li class="d-flex align-items-center"><i class="bi bi-eye"></i> <a href="{% url 'blog:blog-single' pid=post.id %}">{{post.counted_views}} Views</a></li>
                  <li class="d-flex align-items-center"><i class="bi bi-chat-dots"></i> <a href="{% url 'blog:blog-single' pid=post.id %}">{{comments|length}} Comments</a></li>
                </ul>
              </div>

              <div class="entry-content">
                <p>
                  {{post.content|safe}}
                </p>

              </div>

              <div class="entry-footer">
                <i class="bi bi-folder"></i>
                <ul class="cats">
                  {% for cat in post.category.all %}
                    <li><a href="{% url 'blog:category' cat_name=cat.name %}">
                        {{cat.name}} {% if not forloop.last %},{% endif %}
                    </a></li>
                  {% endfor %}
                </ul>
              </div>

            </article><!-- End blog entry -->

            <div class="blog-author d-flex align-items-center">
              <img src="{% static 'assets/img/blog/blog-author.jpg' %}" class="rounded-circle float-left" alt="">
              <div>
                <h4>Reza Mousavi</h4>
                <div class="social-links">
                  <a href="https://twitters.com/#"><i class="bi bi-twitter"></i></a>
                  <a href="https://facebook.com/#"><i class="bi bi-facebook"></i></a>
                  <a href="https://instagram.com/#"><i class="biu bi-instagram"></i></a>
                </div>
                <p>
                  My name is Reza Mousavi, born in Kashan, Isfahan, grew up in Kermanshah. I used to be a front-end developoer. Now I am interested in back-end and I am learning Django.
                </p>
              </div>
            </div><!-- End blog author bio -->

            <div class="blog-author navigation-area d-flex align-items-center">
              <div class="row">
                <br>
                <div class="col-lg-6 col-md-6 col-12 nav-left flex-row d-flex justify-content-start align-items-center">
                    {% if previous_post %}
                      <div class="thumb col-md-4">
                        <a href="{% url 'blog:blog-single' previous_post.id %}"><img
                            class="img-fluid img-responsive"
                            src="{{previous_post.image.url}}"
                            alt=""/></a>
                      </div>
                      <div class="arrow">
                        <a href="{% url 'blog:blog-single' previous_post.id %}"
                          ><span class="lnr text-white lnr-arrow-left"></span
                        ></a>
                      </div>
                      <div class="detials">
                        <p>Prev Post</p>
                        <a href="{% url 'blog:blog-single' previous_post.id %}"><h4>{{previous_post.title}}</h4></a>
                      </div>
                    {% endif %}
                  </div>
                

                  <div class="col-lg-6 col-md-6 col-12 nav-right flex-row d-flex justify-content-end align-items-center">
                    {% if next_post %}
                    <div class="detials ml-auto">
                      <p>Next Post</p>
                      <a href="{% url 'blog:blog-single' next_post.id %}"><h4>{{next_post.title}}</h4></a>
                    </div>
                    <div class="arrow">
                      <a href="{% url 'blog:blog-single' next_post.id %}"><span class="lnr text-white lnr-arrow-right"></span></a>
                    </div>
                    <div class="thumb col-md-4">
                      <a href="{% url 'blog:blog-single' next_post.id %}"><img
                          class="img-fluid img-responsive"
                          src="{{next_post.image.url}}"
                          alt=""/></a>
                    </div>
                    {% endif %}
                  </div>
              </div>
            </div>

            <br>
            <br>

            <div class="blog-comments">

              <h4 class="comments-count">{{comments|length}} Comments</h4>
              {% for comment in comments %}
              
                <div id="comment-1" class="comment">
                  <div class="d-flex">
                    <div class="comment-img"><img src="{% static 'assets/img/blog/user-icon.png' %}" alt=""></div>
                    <div>
                      <h5><a href="">{{comment.name}}</a>
                        {% comment %} <a href="#" class="reply"><i class="bi bi-reply-fill"></i> Reply</a> {% endcomment %}
                      </h5>
                      <small><time datetime="2020-01-01">{{comment.created_date|naturalday}}</time></small>
                      <p>
                        {{comment.message}}
                      </p>
                    </div>
                  </div>
                </div><!-- End comment #1 -->
                {% empty %}
                <p>No comments here. Be the first one leave a comment...</p>
              {% endfor %}
              <div class="reply-form">
                <h4>Leave a Comment</h4>
                <p>Your email address will not be published. Required fields are marked * </p>
                <form method='post' action="{% url 'blog:blog-single' pid=post.id %}">
                  {% csrf_token %}
                  <input type="hidden" name='post' value={{post.id}}>
                  {% if request.user.is_authenticated %}
                  <div class="row">
                    <div class="col-md-6 form-group">
                      <input type="hidden" name="name" value={{request.user.firt_name}} class="form-control" placeholder="Your Name*">
                    </div>
                    <div class="col-md-6 form-group">
                      <input type="hidden" name="email" value={{request.user.email}} class="form-control" placeholder="Your Email*">
                    </div>
                  </div>
                  {% else %}
                  <div class="row">
                    <div class="col-md-6 form-group">
                      <input name="name" type="text" class="form-control" placeholder="Your Name*">
                    </div>
                    <div class="col-md-6 form-group">
                      <input name="email" type="email" class="form-control" placeholder="Your Email*">
                    </div>
                  </div>
                  {% endif %}
                  <div class="row">
                    <div class="col form-group">
                      <input name="subject" type="text" class="form-control" placeholder="Subject*">
                    </div>
                  </div>
                  <div class="row">
                    <div class="col form-group">
                      <textarea name="message" class="form-control" placeholder="Your Comment*"></textarea>
                    </div>
                  </div>
                  
                  <button type="submit" class="btn btn-primary">Post Comment</button>

                </form>

              </div>

            </div><!-- End blog comments -->

          </div><!-- End blog entries list -->

          <div class="col-lg-4">

            <div class="sidebar">

              {% include 'blog/blog-search.html' %}

              {% postcategories %}

              {% recentposts %}

              {% include 'blog/blog-tags.html' %}

            </div><!-- End sidebar -->

          </div><!-- End blog sidebar -->

        </div>

      </div>
    </section><!-- End Blog Single Section -->

  </main><!-- End #main -->

  {% endblock %}

templates/blog/blog-tags.html
<h3 class="sidebar-title">Tags</h3>
              <div class="sidebar-item tags">
                <ul>
                  {% for tag in post.tags.all %}
                    <li><a href="{% url 'blog:tag' tag_name=tag.name %}">{{tag.name}}</a></li>
                  {% endfor %}
                </ul>
              </div><!-- End sidebar tags-->

templates/blog/blog.html
{% extends 'base.html' %}
{% load humanize %}
{% load static %}
{% load blog_tags %}
{% block content %}

  <main id="main">

    <!-- ======= Blog Section ======= -->
    <section class="breadcrumbs">
      <div class="container">

        <div class="d-flex justify-content-between align-items-center">
          <h2>Blog</h2>

          <ol>
            <li><a href="{% url 'website:index' %}">Home</a></li>
            <li>Blog</li>
          </ol>
        </div>

      </div>
    </section><!-- End Blog Section -->

    <!-- ======= Blog Section ======= -->
    <section id="blog" class="blog">
      <div class="container" data-aos="fade-up">

        <div class="row">

          <div class="col-lg-8 entries">
            {% for post in posts %}
            <article class="entry">

              <div class="entry-img">
                <img src="{{post.image.url}}" alt="" class="img-fluid">
              </div>

              <h2 class="entry-title">
                <a href="{% url 'blog:blog-single' pid=post.id %}">{{post.title}}</a>
              </h2>

              <div class="entry-meta">
                <ul class="cats">
                  <span>Categories:&nbsp&nbsp</span>
                  {% for cat in post.category.all %}
                    <li><a href="{% url 'blog:category' cat_name=cat.name %}">
                        {{cat.name}} {% if not forloop.last %},{% endif %}
                    </a></li>
                  {% endfor %}
                </ul>
                <br>
                <ul>
                  <li class="d-flex align-items-center"><i class="bi bi-person"></i> <a href="{% url 'blog:author' author_username=post.author.username %}">{{post.author.get_full_name}}</a></li>
                  <li class="d-flex align-items-center"><i class="bi bi-clock"></i> <a href="{% url 'blog:blog-single' pid=post.id %}"><time datetime="2020-01-01">{{post.published_date|naturaltime}}</time></a></li>
                  <li class="d-flex align-items-center"><i class="bi bi-eye"></i> <a href="{% url 'blog:blog-single' pid=post.id %}">{{post.counted_views}} Views</a></li>
                  <li class="d-flex align-items-center"><i class="bi bi-chat-dots"></i> <a href="{% url 'blog:blog-single' pid=post.id %}">{% comments_count post.id %} Comments</a></li>
                </ul>
              </div>

              <div class="entry-content">
                <p>
                  {{post.content|truncatewords:20}}
                </p>
                <div class="read-more">
                  <a href="{% url 'blog:blog-single' pid=post.id%}">Read More</a>
                </div>
              </div>

            </article><!-- End blog entry -->
            {% endfor %}
            <div class="blog-pagination">
              <ul class="justify-content-center">
                
                {% if posts.has_previous %}
                  <li><a href="?page=1">First</a></li>
                  <li><a href="?page={{posts.previous_page_number}}">Previous</a></li>
                {% endif %}
                {% for i in posts.paginator.page_range %}
                  {% if posts.number == i %}
                    <li class='active'><a href="?page={{i}}">{{i}}</a></li>
                    {% else %}
                    <li><a href="?page={{i}}">{{i}}</a></li>
                  {% endif %}
                {% endfor %}
                {% if posts.has_next %}
                  <li><a href="?page={{posts.next_page_number}}">Next</a></li>
                  <li><a href="?page={{posts.paginator.num_pages}}">Last</a></li>
                {% endif %}
              </ul>
            </div>

          </div><!-- End blog entries list -->

          <div class="col-lg-4">

            <div class="sidebar">

              {% include 'blog/blog-search.html' %}

              {% postcategories %}

              {% recentposts %}

            </div><!-- End sidebar -->

          </div><!-- End blog sidebar -->

        </div>

          </div><!-- End blog sidebar -->

        </div>

      </div>
    </section><!-- End Blog Section -->

  </main><!-- End #main -->

  {% endblock %}